# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1.4.1
      - name: build
        run: |
          cl /EHsc hello.cpp
      - name: ls
        run: ls
       
      - name: "Artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: "*.exe"
          retention-days: 3
          
  send:
     needs: build
     runs-on: ubuntu-latest

     steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
         name: my-artifact

      - name: send artifact to tg
        uses: appleboy/telegram-action@master
        with:
         to: 830735596
         token: 1766024555:AAEh5UE9n7n1FGIGYMsmjMPBDpXMvJJuoss
         document: hello.exe
